version: 0.1
environment_variables:
  plaintext:
    FUNCTION_NAME: SlackSNS
phases:
  install:
    commands:
      - echo Install started on `date`
      - apt-get update -y
      - apt-get install -y zip
  pre_build:
    commands:
      - echo Prebuild started on `date`
  build:
    commands:
      - echo Build started on `date`
      - zip function.zip lambda_function.py
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://function.zip
  post_build:
    commands:
      - echo Post-build started on `date`
artifacts:
  files:
    - '**/*'