AWSTemplateFormatVersion: 2010-09-09

Description: |
  Creates a Lambda function and role for the Slack integration service.

Parameters:
  Environment:
    Description: "The environment e.g. dev, test, prod"
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
  SlackChannel:
    Type: String
    Description: The Slack Channel to send notifications to
  KmsKeyArn:
    Type: String
    Description: The ARN of the KMS key used to encrypt the hook URL
  KmsEncryptedHookUrl:
    Type: String
    Description: The encrypted hook URL.

Resources:
  SnsTopic:
    DependsOn: LambdaFunction
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: Slack
      Subscription:
        - Endpoint: !GetAtt
            - LambdaFunction
            - Arn
          Protocol: lambda
      TopicName: Slack

  SnsInvokePermission:
    DependsOn: LambdaFunction
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: sns.amazonaws.com
      SourceArn: !Ref SnsTopic
      FunctionName: Slack

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: function.zip
      Description: Lambda function for Slack integrations
      FunctionName: SlackSNS
      Handler: lambda_function.lambda_handler
      Role: !GetAtt 
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          slackChannel: !Ref SlackChannel
          kmsEncryptedHookUrl: !Ref KmsEncryptedHookUrl
          ENVIRONMENT: !Ref Environment
      Runtime: python2.7
      MemorySize: '128'
      Timeout: '3'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: SlackSNS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'kms:Decrypt'
                Resource: !Ref KmsKeyArn

